# Generated by Django 4.1.6 on 2023-03-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_remove_agent_clusters'),
        ('clusters', '0002_cluster_encounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='clusters', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='cluster',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agent'),
        ),
    ]
