# Generated by Django 4.1.6 on 2023-03-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0003_cluster_agents_cluster_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='timers',
            field=models.JSONField(null=True),
        ),
    ]
