# Generated by Django 4.1.6 on 2023-03-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agent_action_agent_aggro_agent_armor_class_and_more'),
        ('clusters', '0004_cluster_timers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
    ]
