# Generated by Django 4.1.6 on 2023-03-08 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_agent_name_alter_agent_type'),
        ('clusters', '0005_alter_cluster_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='timers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
