# Generated by Django 4.1.6 on 2023-03-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0006_alter_cluster_name_alter_cluster_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
