# Generated by Django 4.1.6 on 2023-03-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0007_alter_cluster_name_alter_cluster_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='timers',
        ),
        migrations.AddField(
            model_name='cluster',
            name='expiry',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='reminderAllEnd',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='reminderAllStart',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='reminderMemberEnd',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='reminderMemberStart',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='reminderOwnerEnd',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='reminderOwnerStart',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='reminderText',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='timerCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='timerTerm',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
