# Generated by Django 4.1.6 on 2023-03-09 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0009_rename_reminderallend_cluster_reminder_all_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='timer_term',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
