# Generated by Django 4.1.6 on 2023-03-09 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0010_alter_cluster_timer_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cluster',
            old_name='reminder_member_mtart',
            new_name='reminder_member_start',
        ),
    ]
