# Generated by Django 4.1.6 on 2023-03-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0011_rename_reminder_member_mtart_cluster_reminder_member_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='reminder_round_end',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cluster',
            name='reminder_round_start',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
