from clusters.models import Cluster

default_clusters = []

default_clusters.append(Cluster(None, "Heroes", "faction", None))
default_clusters.append(Cluster(None, "Allies", "faction", None))
default_clusters.append(Cluster(None, "Enemies", "faction", None))
default_clusters.append(Cluster(None, "Neutral", "faction", None))
default_clusters.append(Cluster(None, "Blinded", "condition", None))
default_clusters.append(Cluster(None, "Charmed", "condition", None))
default_clusters.append(Cluster(None, "Deafened", "condition", None))
default_clusters.append(Cluster(None, "Frightened", "condition", None))
default_clusters.append(Cluster(None, "Grappled", "condition", None))
default_clusters.append(Cluster(None, "Incapacitated", "condition", None))
default_clusters.append(Cluster(None, "Invisible", "condition", None))
default_clusters.append(Cluster(None, "Paralyzed", "condition", None))
default_clusters.append(Cluster(None, "Petrified", "condition", None))
default_clusters.append(Cluster(None, "Poisoned", "condition", None))
default_clusters.append(Cluster(None, "Prone", "condition", None))
default_clusters.append(Cluster(None, "Restrained", "condition", None))
default_clusters.append(Cluster(None, "Stunned", "condition", None))
default_clusters.append(Cluster(None, "Unconscious", "condition", None))
default_clusters.append(Cluster(None, "Exhaustion", "condition", None))
default_clusters.append(Cluster(None, "Lightly-obscured", "status", None))
default_clusters.append(Cluster(None, "Heavily-obscured", "status", None))
default_clusters.append(Cluster(None, "Bright light", "status", None))
default_clusters.append(Cluster(None, "Dim light", "status", None))
default_clusters.append(Cluster(None, "Darkness", "status", None))
default_clusters.append(Cluster(None, "Suffocating", "status", None))
default_clusters.append(Cluster(None, "Concentrating", "status", None))
default_clusters.append(Cluster(None, "Surprised", "status", None))
default_clusters.append(Cluster(None, "1/2 cover", "status", None))
default_clusters.append(Cluster(None, "3/4 cover", "status", None))
default_clusters.append(Cluster(None, "Full cover", "status", None))
default_clusters.append(Cluster(None, "Hiding", "status", None))
default_clusters.append(Cluster(None, "Dead", "status", None))
default_clusters.append(Cluster(None, "Dying", "status", None))
default_clusters.append(Cluster(None, "In melee", "location", None))
default_clusters.append(Cluster(None, "At range", "location", None))
default_clusters.append(Cluster(None, "Fleeing", "location", None))
default_clusters.append(Cluster(None, "placeholder", "system", None))


