from django.db import models
from encounters.models import Encounter

class Agent(models.Model):
    encounter = models.ForeignKey(Encounter, related_name="agents", on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=100)
    alias = models.CharField(max_length=100, null=True, blank=True)
    type = models.CharField(max_length=100)
    notes = models.TextField(max_length=1024, null= True, blank=True)
    str_save = models.IntegerField(null=True, blank=True)
    dex_save = models.IntegerField(null=True, blank=True)
    con_save = models.IntegerField(null=True, blank=True)
    int_save = models.IntegerField(null=True, blank=True)
    wis_save = models.IntegerField(null=True, blank=True)
    cha_save = models.IntegerField(null=True, blank=True)
    passive_insight = models.IntegerField(null=True, blank=True)
    passive_investigation = models.IntegerField(null=True, blank=True)
    passive_perception = models.IntegerField(null=True, blank=True)
    initiative = models.IntegerField(null=True, blank=True)
    initiative_bonus = models.IntegerField(default=0, blank=True)
    max_hit_points = models.IntegerField(null=True, blank=True)
    hit_points = models.IntegerField(null=True, blank=True)
    armor_class = models.IntegerField(null=True, blank=True)
    attack_bonus = models.IntegerField(default=0, blank=True)
    spell_save = models.IntegerField(null=True, blank=True)
    action = models.BooleanField(default=True)
    move = models.BooleanField(default=True)
    bonus = models.BooleanField(default=True)
    reaction = models.BooleanField(default=True)
    free = models.BooleanField(default=True)
    exclamation = models.BooleanField(default=True)
    aggro = models.ForeignKey("self", on_delete=models.SET_NULL, null= True, blank=True)