# Generated by Django 4.1.6 on 2023-02-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agent_clusters'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='initiative',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='initiative_bonus',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
