# Generated by Django 4.1.6 on 2023-03-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_initiative_agent_initiative_bonus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='clusters',
        ),
    ]
