# Generated by Django 4.1.6 on 2023-03-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_agent_aggro_alter_agent_armor_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='agent',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
