# Generated by Django 4.1.6 on 2023-03-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_alter_agent_initiative_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
