# Generated by Django 4.1.6 on 2023-03-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_agent_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='notes',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
