# Generated by Django 4.1.6 on 2023-03-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_alter_agent_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='attack_bonus',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='initiative_bonus',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
