# Generated by Django 4.1.6 on 2023-02-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_clusters'),
        ('clusters', '0001_initial'),
        ('encounters', '0004_encounter_agents_encounter_clusters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='agents',
            field=models.ManyToManyField(blank=True, to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='clusters',
            field=models.ManyToManyField(blank=True, to='clusters.cluster'),
        ),
    ]
