# Generated by Django 4.1.6 on 2023-03-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0006_remove_encounter_agents_remove_encounter_clusters'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
