export const GET_ENCOUNTERS = "GET_ENCOUNTERS";
export const ADD_ENCOUNTER = "ADD_ENCOUNTER";
export const DELETE_ENCOUNTER = "DELETE_ENCOUNTER";
export const UPDATE_ENCOUNTER = "UPDATE_ENCOUTER";
export const SELECT_ENCOUNTER = "SELECT_ENCOUNTER";
export const RUN_ENCOUNTER = "RUN_ENCOUNTER";
export const IMPORT_AGENT = "IMPORT_AGENT";
export const CLUSTER_AGENTS = "CLUSTER_AGENTS";

export const GET_AGENTS = "GET_AGENTS";
export const ADD_AGENT = "ADD_AGENT";
export const DELETE_AGENT = "DELETE_AGENT";
export const UPDATE_AGENT = "UPDATE_AGENT";
export const SELECT_AGENT = "SELECT_AGENT";
export const ACTIVATE_AGENT = "ACTIVATE_AGENT";
export const TOGGLE_CLUSTER_MEMBERSHIP = "TOGGLE_CLUSTER_MEMBERSHIP";

export const GET_CLUSTERS = "GET_CLUSTERS";
export const ADD_CLUSTER = "ADD_CLUSTER";
export const DELETE_CLUSTER = "DELETE_CLUSTER";
export const UPDATE_CLUSTER = "UPDATE_CLUSTER";
export const SELECT_CLUSTER = "SELECT_CLUSTER";
export const QUICK_CLUSTER = "QUICK_CLUSTER";
export const GET_CLUSTER_AGENTS = "GET_CLUSTER_AGENTS";

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const CREATE_REMINDER = "CREATE_REMINDER";
export const TOGGLE_IN_GAME = "TOGGLE_IN_GAME";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATTION_FAIL = "REGISTRATION_FAIL";

export const SET_ACTIVE_NAVLINK = "SET_ACTIVE_NAVLINK";
